name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.5-python3.11
    env:
      UV_CACHE_DIR: .uv-cache
      UV_LINK_MODE: copy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Check formatting
        run: ruff format --check .